const { user } = useUserContext();

  const signOut = useCallback(async () => {
    try {
      await Auth.signOut();
    } catch (e) {
      console.error(e);
    }
  }, []);
